enum MODULES_ENUM {
  RH = 'RH',
  PUESTOS = 'PUESTOS',
  DIRECCIONES = 'DIRECCIONES',
  ORGANIGRAMA = 'ORGANIGRAMA',
  EMPLEADOS = 'EMPLEADOS',
  DOCUMENTOS = 'DOCUMENTOS',
  SOLICITUD_PERMISOS = 'SOLICITUD_PERMISOS',
  SOLICITUD_VACACIONES = 'SOLICITUD_VACACIONES',
  ASIGNACION_A_PROYECTOS = 'ASIGNACION_A_PROYECTOS',
  CIERRE_PROYECTOS = 'CIERRE_PROYECTOS',
  ASISTENCIA = 'ASISTENCIA',
  DIAS_FESTIVOS = 'DIAS_FESTIVOS',
  NOMINAS = 'NOMINAS',
  BONOS = 'BONOS',
  TIPOS_BONOS = 'TIPOS_BONOS',
  DESCRIPCION_BONOS = 'DESCRIPCION_BONOS',
  FIRMAS = 'FIRMAS',
  BANCOS = 'BANCOS',
  TIPOS_DOCUMENTOS = 'TIPOS_DOCUMENTOS',
  CONTRATOS = 'CONTRATOS',
  TIPOS_CONTRATOS = 'TIPOS_CONTRATOS',
}

enum PERMISSIONS_ENUM {
  VER = 'VER',
  CREAR = 'CREAR',
  EDITAR = 'EDITAR',
  ELIMINAR = 'ELIMINAR',
  RESTAURAR = 'RESTAURAR',
}

const MODULES_MAP: Record<number, MODULES_ENUM> = {
  1: MODULES_ENUM.RH,
  2: MODULES_ENUM.PUESTOS,
  3: MODULES_ENUM.DIRECCIONES,
  4: MODULES_ENUM.ORGANIGRAMA,
  5: MODULES_ENUM.EMPLEADOS,
  6: MODULES_ENUM.DOCUMENTOS,
  7: MODULES_ENUM.SOLICITUD_PERMISOS,
  8: MODULES_ENUM.SOLICITUD_VACACIONES,
  9: MODULES_ENUM.ASIGNACION_A_PROYECTOS,
  10: MODULES_ENUM.CIERRE_PROYECTOS,
  11: MODULES_ENUM.ASISTENCIA,
  12: MODULES_ENUM.DIAS_FESTIVOS,
  13: MODULES_ENUM.NOMINAS,
  14: MODULES_ENUM.BONOS,
  15: MODULES_ENUM.TIPOS_BONOS,
  16: MODULES_ENUM.DESCRIPCION_BONOS,
  17: MODULES_ENUM.FIRMAS,
  18: MODULES_ENUM.BANCOS,
  19: MODULES_ENUM.TIPOS_DOCUMENTOS,
  20: MODULES_ENUM.CONTRATOS,
  21: MODULES_ENUM.TIPOS_CONTRATOS,
};

const PERMISSIONS_MAP: Record<number, PERMISSIONS_ENUM> = {
  1: PERMISSIONS_ENUM.VER,
  2: PERMISSIONS_ENUM.CREAR,
  3: PERMISSIONS_ENUM.EDITAR,
  4: PERMISSIONS_ENUM.ELIMINAR,
  5: PERMISSIONS_ENUM.RESTAURAR,
};

export {
  MODULES_ENUM,
  PERMISSIONS_ENUM,
  MODULES_MAP,
  PERMISSIONS_MAP
}