export enum ASSIGNMENT_STATUS {
  ASIGNACION = 'ASIGNACION',
  DEVOLUCION = 'DEVOLUCION',
}
export enum STATUS_RESOURCE {
  TRAYECTO = 'TRAYECTO',
  ALMACEN = 'ALMACEN',
  DISPONIBLE = 'DISPONIBLE',
}

export enum ADD_REMOVE {
  ALTA = 'ALTA',
  BAJA = 'BAJA',
}   