export enum Status {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum STATUS_PROJECT {
  EVALUATION = 'EVALUATION',
  NO_ACCEPT = 'NO_ACCEPT',
  ACCEPT = 'ACCEPT',
  ACTIVE = 'ACTIVE',
  FINALIZED = 'FINALIZED',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum STATUS_USER {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  FIRST_ACCESS = 'FIRST_ACCESS',
}

export enum STATUS_EMPLOYEE {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PEMISSION = 'PERMISSION',
  DELETED = 'DELETED',
  DISMISSAL = 'DISMISSAL',
}

export enum NACIONALITY_EMPLOYEE {
  MEXICAN = 'Mexicana',
  FOREIGN = 'Extranjera',
}

export enum BLOOD_TYPE {
  A = 'A+',
  AN = 'A-',
  B = 'B+',
  BN = 'B-',
  AB = 'AB+',
  ABN = 'AB-',
  O = 'O+',
  ON = 'O-',
  UNKNOWN = 'Desconocido',
}

export enum GENDER {
  FEMALE = 'Femenino',
  MALE = 'Masculino',
}

export enum STATUS_CIVIL {
  SINGLE = 'Soltero/a',
  MARRIED = 'Casado/a',
  DIVORCED = 'Divorciado/a',
  WIDOWED = 'Viudo/a',
  SEPARATED = 'Separado/a',
  CONDOM = 'Concubino/a',
}

export enum ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum PRESENCE_REASON {
  AUSENCE = 'AUSENCE',
  PRESENCE = 'PRESENCE',
  PERMISSION = 'PERMISSION',
  PERMISSION_NOT_PRESENCE = 'PERMISSION_NOT_PRESENCE',
  PERMISSION_NOT_JUSTIFICATE = 'PERMISSION_NOT_JUSTIFICATE',
  PERMISSION_JUSTIFICATE = 'PERMISSION_JUSTIFICATE',
  VACATION = 'VACATION',
}

export enum STATUS_VACATIONS_PERMISSION {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ATTENDANCE_PERMISSION_TYPE {
  HOURS = 'HOURS',
  DAYS = 'DAYS',
  OTHER = 'OTHER',
}

